version: '3.1'

services:
        db:
                container_name: fidelity_db
                image: postgres
                restart: unless-stopped
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_DB: fidelity-prod
                volumes:
                        - db:/var/lib/postgresql/data
                ports:
                        - "5432:5432"
        
        adminer:
                image: adminer
                restart: unless-stopped
                ports:
                        - "8080:8080"

        fidelity-app:
                container_name: fidelity-app
                build:
                        context: .
                        dockerfile: ./images/Dockerfile
                ports:
                        - "4000:4000"
                depends_on:
                        - db
volumes:
        db:
