version: '3.1'

services:
        db:
                container_name: fidelity_db
                image: postgres
                restart: unless-stopped
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_DB: fidelity-prod
                volumes:
                        - db-data:/var/lib/postgresql/data
                ports:
                        - "5432:5432"
        
        adminer:
                image: adminer
                restart: unless-stopped
                ports:
                        - "8080:8080"

        rabbitmq:
                image: rabbitmq:3.8
                ports:
                        - '5672:5672'
                        - '15672:15672'
                        - '15692:15692'
                volumes:
                        - ./docker/rabbitmq/plugins:/etc/rabbitmq/enabled_plugins
                        - ./docker/rabbitmq/definitions_fidelity.json:/etc/rabbitmq/definitions.json
                        - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
                        - rabbitmq-data:/var/lib/rabbitmq



        # fidelity-app:
        #         container_name: fidelity-app
        #         build:
        #                 context: .
        #                 dockerfile: ./images/Dockerfile
        #         ports:
        #                 - "4000:4000"
        #         depends_on:
        #                 - db

volumes:
  db-data: {}
  rabbitmq-data: {}
